config/routes.rb
Rails.application.routes.draw do
  get 'shoping_list/index'
  get 'recipe_foods/new'
  get 'recipes/index'
  get 'recipes/show'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  devise_scope :user do
    authenticated :user do
      root :to => 'foods#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'recipes#public_recipes', as: :unauthenticated_root
    end
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  resources :foods, only: [:index, :new, :create, :destroy]
  resources :recipes, only: [:index, :new, :create, :destroy, :show] do
  resources :recipe_foods, only: [:new,:create, :destroy]
  end
  resources :shoping_list, only: [:index]

  get '/public_recipes', to: 'recipes#public_recipes', as: 'public_recipes'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    puts "User: #{user.inspect}"
    can :public_recipes, Recipe
    can :read, Recipe, public: true
    return unless user.present?

    can :manage, Recipe, users_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
    validates :name, :measurement_unit, :quantity, presence: true
    validates :price, presence: true, numericality: {greater_than: 0}
    has_many :recipe_foods, foreign_key: "foods_id", dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, :cooking_time, :preperation_time, :description, presence: true
    attribute :public, :boolean, default: true

    belongs_to :user, foreign_key: 'users_id'
    has_many :recipe_foods, foreign_key: 'recipes_id', dependent: :destroy
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
    validates :quantity, presence: true
    belongs_to :food, foreign_key: "foods_id", dependent: :destroy
    belongs_to :recipe, foreign_key: "recipes_id", dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  
   has_many :foods, foreign_key: 'users_id'
   has_many :recipes, foreign_key: 'users_id'

    validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # protect_from_forgery with: :null_session
    before_action :update_allowed_parameters, if: :devise_controller?

    protected

    def update_allowed_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :passwrod, :current_password)}
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
    def index
        @foodlist = current_user.foods
    end

    def new
        @food = Food.new
    end

    def create
        @food = Food.new(food_parms)
        @food.users_id = current_user.id;

        if @food.save
            redirect_to foods_path, notice: 'Food succesfully created'
        else
            render :new
        end
    end
    
    def destroy
        @food = Food.find(params[:id])
        if @food.destroy
            redirect_to foods_path, notice: 'Food succesfully deleted'
        else
            redirect_to foods_path, alert: 'Failed to delete food'
        end
    end

    private
    
    def food_parms
        params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
    end

end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe_food = RecipeFood.new
  end

  def create
     @recipe_food = RecipeFood.new(recipe_food_params)
     @recipe_food.recipes_id = params[:recipe_id]
     if @recipe_food.save
      redirect_to recipe_path(@recipe_food.recipes_id), notice: 'Ingredient added successfully'
    else
      puts "Errors: #{@recipe_food.errors.full_messages}"
      render :new, notice: 'Ingredient added successfully'
    end
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    redirect_to recipe_path(@recipe_food.recipes_id)
  end

  private

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity, :foods_id)
  end
  
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  load_and_authorize_resource
  
  def index
    @recipes = current_user.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
    @recipe_foods = RecipeFood.where(recipes_id: params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.users_id = current_user.id;
    
    if @recipe.save
      redirect_to recipes_path, notice: "Recipe succesfully created"
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      redirect_to recipes_path, notice: "Recipe removed successfully"
    end
  end

  def public_recipes
    authorize! :public_recipes, Recipe
    @recipes = Recipe.where(public: true).order(id: :asc)
  end

  private

  def recipe_params
     params.require(:recipe).permit(:name, :cooking_time, :preperation_time, :description, :public)
   end
  
end

app/controllers/shoping_list_controller.rb
class ShopingListController < ApplicationController
  def index
    @user = current_user
    @recipes = Recipe.where(users_id: @user.id)
    @missing_numbers = {}
    @ingredients = RecipeFood.where(recipe: @recipes).group_by { |ingredient| ingredient.food.name }

    @total_price = @ingredients.map do |food_name, ingredients|
      total_quantity_required = ingredients.sum(&:quantity)
      user_food = @user.foods.find_by(name: food_name)
      missing_quantity = user_food ? [total_quantity_required - user_food.quantity, 0].max : total_quantity_required
      @missing_numbers[food_name] = missing_quantity
      missing_quantity * ingredients.first.food.price
    end.sum
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shoping_list_helper.rb
module ShopingListHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<h1>Food list</h1>
<%= link_to "Add Food", new_food_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Measurement Unit</th>
      <th>Quantity</th>
      <th>Price</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @foodlist.each do |food| %>
        <tr>
        <td><%= food.name %></td>
        <td><%= food.measurement_unit %></td>
        <td><%= food.quantity %></td>
        <td><%= food.price %></td>
        <td>
           <%= button_to "Delete", food, method: :delete, data: {confirm: "Are your sure"} %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/foods/new.html.erb
<h1>Add Food</h1>

<%= form_for @food do |f|%>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :measurement_unit %>
    <%= f.text_field :measurement_unit %>
  </div>

  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div>
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>

  <div>
    <%= f.submit "Create Food" %>
  </div>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/recipe_foods/new.html.erb
<h1>RecipeFoods</h1>

<%= form_for  @recipe_food, url: recipe_recipe_foods_path do |form| %>

    <%= form.label :quantity %>
    <%= form.number_field :quantity, min: 1, value: 1, required: true %>
    <%= form.collection_select :foods_id, current_user.foods, :id, :name, { include_blank: false } %> 
    <%= link_to "Add new food", new_food_path %>
    <%= form.submit "Add ingredient" %>
    
<% end %>
  

app/views/recipes/index.html.erb
<h1>Recipes</h1>
<%= link_to "Add Recipe", new_recipe_path %>


<ul>
  <% if @recipes.any?%>
      <% @recipes.each do |recipe| %>
        <li>
         <h2><%= link_to recipe.name, recipe_path(recipe.id) %></h2>
         <%= recipe.description %> <br>
         <%= button_to "Delete", recipe, method: :delete, data: {confirm: "Are your sure"} %>
        </li>
      <%end%>
  <%else%>
     <li>
       No  recipes added by you
     </li>
  <%end%>
</ul>

app/views/recipes/new.html.erb
<h1>Add recipe details</h1>

<%= form_with model: [@recipe], data: { turbo: false }, local: true do |f| %>
        
   <%= f.label :name, "name" %> <br>
   <%= f.text_field :name %> <br>

   <%= f.label :cooking_time %> <br>
   <%= f.number_field :cooking_time %> <br>

   <%= f.label :preparation_time %> <br>
   <%= f.number_field :preperation_time %> <br>

   <%= f.label :description %> <br>
   <%= f.text_field :description %> <br>

   <%= f.label :public %> <br>
   <%= f.check_box :public %><br>

   <%= f.submit "Create Recipe" %>
    
   <br>
<% end %>

app/views/recipes/public_recipes.html.erb
<h1>Public Recipes</h1>

<ul id="recipes_container">
  <% @recipes.includes([:user]).includes([:recipe_foods]).each do |recipe| %>
    <li class="single_recipe">
      <%= link_to "/recipes/#{recipe.id}" do %>
        <h2><%= recipe.name %> by <%= recipe.user.name %></h2>
      <% end %>
      <% if can? :destroy, recipe %>
        <%= form_with model: recipe, url: recipe_path(recipe), method: :delete do |f| %>
          <%= f.submit "REMOVE" %>
        <% end %>
      <% end %>
      <p>Total food items: <%= recipe.recipe_foods.length %></p>
      <p>Total price: <%= recipe.recipe_foods.sum { |recipe_food| recipe_food.food.price * recipe_food.quantity} %></p>
    </li>
  <% end %>

app/views/recipes/show.html.erb
<div>
   <h1><%= @recipe.name%> </h1>
   <%if @recipe.public%>
      Public
    <%else%>
      private
    <%end%>
   <p>Preparation time: <%= @recipe.preperation_time %> <%= "hour".pluralize(@recipe.preperation_time) %></p>
   <p>Cooking time: <%= @recipe.cooking_time %> <%= "hour".pluralize(@recipe.cooking_time) %></p>
   <p> <%= @recipe.description%> </p>

   <% if current_user == @recipe.user %>
   <div id="recipe_actions">
     <%= link_to "Generate shopping list", foods_path %>
     <%= link_to "Add ingredient", new_recipe_recipe_food_path(@recipe.id) %>
   </div>
   <% end %>

   <table>
   <thead>
     <tr>
       <th>Food</th>
       <th>Quantity</th>
       <th>Value</th>
       <th>Action</th>
     </tr>
   </thead>
   <tbody>
     <% @recipe_foods.each do |food| %>
         <tr>
         <td><%= food.food.name %></td>
         <td><%= food.quantity %></td>
         <td><%= food.food.price * food.quantity %></td>
         <td>
            <%= button_to "Delete", recipe_recipe_food_path(@recipe, food), method: :delete, data: {confirm: "Are your sure"} %>
         </td>
       </tr>
     <%end%>
   </tbody>
 </table>

</div>

app/views/shared/_navigation.html.erb
<nav class="navbar">
    <%= link_to "Recipe Book", '/public_recipes' %>
      <div class="nav-list">
        <% if user_signed_in? %>
          <%= link_to "Foods", foods_path %>
          <%= link_to "Recipes", recipes_path %>
          <%= link_to "Public Recipes", '/public_recipes' %>
          <%= link_to "Shopping List", '/shoping_list' %>
          <%= button_to "Log Out", destroy_user_session_path, method: :delete %>
        <% else %>
           <% unless user_signed_in? %>
           <%= link_to "Sign In", new_user_session_path %>
           <%= link_to "Sign Up", new_user_registration_path %>
           <% end %>
        <% end %>
      </div>
</nav>

app/views/shoping_list/index.html.erb
<h1>Shopping List</h1>

<p>Amount of Food items to buy: <%= @ingredients.length %> </p>
<p>Total value of Food needed: <%= number_to_currency(@total_price) %> </p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quantity</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    <% @ingredients.each do |food_name, ingredients| %>
      <% ingredients.each do |ingredient| %>
        <tr>
          <td><%= food_name %></td>
          <td><%= @missing_numbers[food_name] %> <%= ingredient.food.measurement_unit %> </td>
          <td><%= number_to_currency(ingredient.food.price * @missing_numbers[food_name]) %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>